theme: jekyll-theme-minimal
title: ğŸ§‘ğŸ¼â€ğŸ’» â˜•ï¸ ğŸƒğŸ¼
description: Sam Brentnall's CV
plugins:
  - jekyll-link-attributes
external_links:
  enabled: true
  rel: me
  target: _blank
  exclude:
